### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by Ingener74** [claws/aioprometheus#99]
Hi. I'm trying to use aioprometheus and get this
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/sample1/app/app.py", line 10, in <module>
    from aioprometheus import REGISTRY, Counter, render
  File "/usr/local/lib/python3.11/site-packages/aioprometheus/__init__.py", line 2, in <module>
    from .collectors import (
  File "/usr/local/lib/python3.11/site-packages/aioprometheus/collectors.py", line 10, in <module>
    from .metricdict import MetricDict
  File "/usr/local/lib/python3.11/site-packages/aioprometheus/metricdict.py", line 12, in <module>
    class MetricDict(collections.MutableMapping):
```
Python 3.11

**Comment by Ingener74** [comment]
Did you tests aioprometheus on Python 3.11?

**Comment by Mirochill** [comment]
I checked the current tree and the `22.5.0` tag, and `src/aioprometheus/metricdict.py` now imports `MutableMapping` from `collections.abc`:

```python
from collections.abc import MutableMapping
```

That fix appears to have landed in #33. If this still reproduces, it is likely coming from an older installed `aioprometheus` package or a stale environment; checking the installed version and upgrading should be the next thing to verify.
